FROM rocker/geospatial
LABEL maintainer="lab1702"


RUN install2.r -e -s -n -1 \
    plotly \
    caret \
    randomForest \
    xgboost \
    etree \
    forecast \
    prophet \
    quantmod \
    PerformanceAnalytics \
    PortfolioAnalytics \
    tidyquant \
    ichimoku \
    binancer \
    shiny \
    shinycssloaders \
    gt \
    gtExtras \
    gtsummary \
    blastula \
    styler
